import { useMDXComponents } from "@/mdx-components.tsx";
import './globals.css';
import Navbar from "@/lib/page_elements";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      < Navbar />
      <body>{children}</body> 
    </html>
  );
}