import { useMDXComponents } from "@/mdx-components.tsx";
import './globals.css';
import Navbar from "@/lib/navbar";
// import "katex/dist/katex.min.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Navbar />
      {children}
      </body> 
    </html>
  );
}
